### ISSUE TITLE
[Bug]: Unfortunate hotbar tooltip glitch with Legendary Tooltips installed

### ISSUE THREAD

**Issue by archiso86** [constellation-mc/andromeda#101]
### What happened?

When Legendary Tooltips mod is installed (doesn't matter the dependencies, cuz i forgot to uninstall them additionally but it still worked) then the hotbar tooltip renderer gets really glitchy and text clips in & out of the box

Also I use Bedrockify and several other mods in the screenshots but I did tests without many other mods (except Sodium and basic performance mods because regardless it should work) and received the same results (broken with Legendary Tooltips, fixed when it is removed)

Really strangely, there is a frame when I switch to another hotbar slot where the tooltip renders how I would expect it to (text INSIDE the box)

After like 3 minutes of having this posted I found out that it seems to be trouble in rendering the attributes such as "+8 Armor" or "+3 Armor Toughness"

Ok, it's posted on the LegendaryTooltips github repo as
https://github.com/AHilyard/LegendaryTooltips/issues/137

## Also `legendarytooltips-common.toml`
https://pastebin.com/SmXXf8V1

### Screenshots

![image](https://github.com/melontini/andromeda/assets/160344941/4ee3ed06-cb2d-45fe-abe8-4fb12a4b89d4)
![image](https://github.com/melontini/andromeda/assets/160344941/5e311ac6-82ec-4586-958d-d2c7ef2733f5)
![image](https://github.com/melontini/andromeda/assets/160344941/46846e63-f35d-4e03-a050-483b95c68131)
![image](https://github.com/melontini/andromeda/assets/160344941/df642c19-ae20-4ac1-9cad-19d2b43ab730)
![image](https://github.com/melontini/andromeda/assets/160344941/430188f6-79ae-4fd3-bb80-638f44f79b92)
![image](https://github.com/melontini/andromeda/assets/160344941/f288c75c-b41c-4dce-b25e-2f8a1eea7850)

### Logs

https://mclo.gs/OvOjvzK  ;  https://mclo.gs/rtUGZT9

### Mod Version

Andromeda 1.6.1-1.20.1, Legendary Tooltips 1.4.4, Iceberg 1.1.18, Prism 1.0.5

### Minecraft Version

Minecraft 1.20.1, Fabric Loader 0.15.6

**Comment by zenfyrdev** [comment]
Hi, thank you for the report. I also recommend opening an issue on LT's issue tracker.

**Comment by ghost** [comment]
Ok, will do

**Comment by zenfyrdev** [comment]
Could you, please, try this build? https://github.com/melontini/andromeda/actions/runs/8098426828

**Comment by ghost** [comment]
Sorry about the late reply, I tested the build you had sent

On a "default" (slightly modded) configuration it works fine, shown in the screenshot:
![image](https://github.com/melontini/andromeda/assets/160344941/6a390a45-0342-4945-a108-3888dd1f66e5)
(albeit I have to turn off name separator or else it appears in the middle, but sacrifices can be made for these two mods)

But in my mod configuration it doesn't work so fine...
![image](https://github.com/melontini/andromeda/assets/160344941/e0538763-71c8-48a6-8eb6-c528a175d46a)
And all the more interestingly and confusingly, it appears that if the tooltip were to have been placed correctly, then the name separator would be correctly placed
But the tooltip background and text were consistently spaced away from the left?

I checked the compatibility with Bedrockify and it does not make a difference on the default config
And in Bedrockify both cases, I disabled this mixin that may be related to the tooltip
![image](https://github.com/melontini/andromeda/assets/160344941/d47a7d17-8bfb-41bc-a4a3-3f528e787989)

Seems to be related to 'Slight GUI Modifications'

But the two mods do work together now with the setting, so I think this issue is complete.
